In [ ]:
#from google.colab import files
#uploaded =  files.upload()
!wget https://raw.githubusercontent.com/SNOWMAN786/pokemon-game/main/pokemon.csv
!wget https://raw.githubusercontent.com/SNOWMAN786/pokemon-game/main/pokemon_classes.py
!wget https://raw.githubusercontent.com/SNOWMAN786/pokemon-game/main/train_ai.py
import pandas as pd
df = pd.read_csv('pokemon.csv')

Saving pokemon.csv to pokemon (4).csv

In [ ]:
#adding the classes

In [ ]:

import numpy as np
import matplotlib as mp
from pokemon_classes import Attack
df=pd.read_csv(r'pokemon.csv')

In [ ]:
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [ ]:
a=np.array(df)

In [ ]:
priority=['name','classfication','speed','base_total','defense','hp','type1','type2']
remaning=[col for col in df.columns if col not in priority]
sortpoke= df[priority+remaning]
sortpoke["type2"]=sortpoke["type2"].fillna(sortpoke["type1"])
print(sortpoke.isnull())#type 2 dealt

      name  classfication  speed  base_total  defense     hp  type1  type2  \
0    False          False  False       False    False  False  False  False
1    False          False  False       False    False  False  False  False
2    False          False  False       False    False  False  False  False
3    False          False  False       False    False  False  False  False
4    False          False  False       False    False  False  False  False
..     ...            ...    ...         ...      ...    ...    ...    ...
796  False          False  False       False    False  False  False  False
797  False          False  False       False    False  False  False  False
798  False          False  False       False    False  False  False  False
799  False          False  False       False    False  False  False  False
800  False          False  False       False    False  False  False  False

     abilities  against_bug  ...  experience_growth  height_m  japanese_name  \
0        False        False  ...              False     False          False
1        False        False  ...              False     False          False
2        False        False  ...              False     False          False
3        False        False  ...              False     False          False
4        False        False  ...              False     False          False
..         ...          ...  ...                ...       ...            ...
796      False        False  ...              False     False          False
797      False        False  ...              False     False          False
798      False        False  ...              False     False          False
799      False        False  ...              False     False          False
800      False        False  ...              False     False          False

     percentage_male  pokedex_number  sp_attack  sp_defense  weight_kg  \
0              False           False      False       False      False
1              False           False      False       False      False
2              False           False      False       False      False
3              False           False      False       False      False
4              False           False      False       False      False
..               ...             ...        ...         ...        ...
796             True           False      False       False      False
797             True           False      False       False      False
798             True           False      False       False      False
799             True           False      False       False      False
800             True           False      False       False      False

     generation  is_legendary
0         False         False
1         False         False
2         False         False
3         False         False
4         False         False
..          ...           ...
796       False         False
797       False         False
798       False         False
799       False         False
800       False         False

[801 rows x 41 columns]

In [ ]:
TYPE_TO_COL = {
    "bug"      : "against_bug",
    "dark"     : "against_dark",
    "dragon"   : "against_dragon",
    "electric" : "against_electric",
    "fairy"    : "against_fairy",
    "fighting" : "against_fight",
    "fire"     : "against_fire",
    "flying"   : "against_flying",
    "ghost"    : "against_ghost",
    "grass"    : "against_grass",
    "ground"   : "against_ground",
    "ice"      : "against_ice",
    "normal"   : "against_normal",
    "poison"   : "against_poison",
    "psychic"  : "against_psychic",
    "rock"     : "against_rock",
    "steel"    : "against_steel",
    "water"    : "against_water",
}

## distribute
 **pokemon**

In [ ]:
#adding the classes

In [ ]:
df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [ ]:
a=np.array(df)

In [ ]:
priority=['name','classfication','speed','base_total','defense','hp','type1','type2']
remaning=[col for col in df.columns if col not in priority]
sortpoke= df[priority+remaning]
sortpoke["type2"]=sortpoke["type2"].fillna(sortpoke["type1"])
print(sortpoke.isnull())#type 2 dealt

      name  classfication  speed  base_total  defense     hp  type1  type2  \
0    False          False  False       False    False  False  False  False
1    False          False  False       False    False  False  False  False
2    False          False  False       False    False  False  False  False
3    False          False  False       False    False  False  False  False
4    False          False  False       False    False  False  False  False
..     ...            ...    ...         ...      ...    ...    ...    ...
796  False          False  False       False    False  False  False  False
797  False          False  False       False    False  False  False  False
798  False          False  False       False    False  False  False  False
799  False          False  False       False    False  False  False  False
800  False          False  False       False    False  False  False  False

     abilities  against_bug  ...  experience_growth  height_m  japanese_name  \
0        False        False  ...              False     False          False
1        False        False  ...              False     False          False
2        False        False  ...              False     False          False
3        False        False  ...              False     False          False
4        False        False  ...              False     False          False
..         ...          ...  ...                ...       ...            ...
796      False        False  ...              False     False          False
797      False        False  ...              False     False          False
798      False        False  ...              False     False          False
799      False        False  ...              False     False          False
800      False        False  ...              False     False          False

     percentage_male  pokedex_number  sp_attack  sp_defense  weight_kg  \
0              False           False      False       False      False
1              False           False      False       False      False
2              False           False      False       False      False
3              False           False      False       False      False
4              False           False      False       False      False
..               ...             ...        ...         ...        ...
796             True           False      False       False      False
797             True           False      False       False      False
798             True           False      False       False      False
799             True           False      False       False      False
800             True           False      False       False      False

     generation  is_legendary
0         False         False
1         False         False
2         False         False
3         False         False
4         False         False
..          ...           ...
796       False         False
797       False         False
798       False         False
799       False         False
800       False         False

[801 rows x 41 columns]

In [ ]:
TYPE_TO_COL = {
    "bug"      : "against_bug",
    "dark"     : "against_dark",
    "dragon"   : "against_dragon",
    "electric" : "against_electric",
    "fairy"    : "against_fairy",
    "fighting" : "against_fight",
    "fire"     : "against_fire",
    "flying"   : "against_flying",
    "ghost"    : "against_ghost",
    "grass"    : "against_grass",
    "ground"   : "against_ground",
    "ice"      : "against_ice",
    "normal"   : "against_normal",
    "poison"   : "against_poison",
    "psychic"  : "against_psychic",
    "rock"     : "against_rock",
    "steel"    : "against_steel",
    "water"    : "against_water",
}

## distribute
 **pokemon**

In [ ]:
player_team = sortpoke.sample(3).reset_index(drop=True)
ai_team     = sortpoke.sample(3).reset_index(drop=True)

In [ ]:
a=player_team.iloc[0]
b=player_team.iloc[1]
c=player_team.iloc[2]

d=ai_team.iloc[0]
e=ai_team.iloc[1]
f=ai_team.iloc[2]
# assigning pokemon done now next step selecting

In [ ]:
class Pokemon:
    def __init__(self, row):
        self.name        = row["name"]
        self.type1       = row["type1"]
        self.type2       = row["type2"]
        self.speed       = row["speed"]
        self.defense     = row["defense"]
        self.sp_defense  = row["sp_defense"]
        self.attack      = row["attack"]
        self.sp_attack   = row["sp_attack"]
        self.base_total  = row["base_total"]
        self.max_hp      = row["hp"]
        self.hp          = row["hp"]
        self._row        = row

    def get_type_multiplier(self, attack_type: str) -> float:
        col = TYPE_TO_COL.get(attack_type)
        if col and col in self._row.index:
            return float(self._row[col])
        return 1.0

    def choose_attack(self) -> str:
        """Player picks between type1 and type2 attack."""
        print(f"\n  [1] {self.type1}   [2] {self.type2}")
        while True:
            try:
                pick = int(input("  Choose attack (1 or 2): "))
                if pick == 1: return self.type1
                if pick == 2: return self.type2
                print("  Enter 1 or 2.")
            except ValueError:
                print("  Invalid — enter a number.")

    def ai_choose_attack(self, opponent: "Pokemon") -> str:
        """
        AI attack selection.
        Uses the trained ML model if available, otherwise falls back to random.
        The features here MUST match exactly what train_ai.py trained on.
        """
        if AI_MODEL is not None:
            mult1 = opponent.get_type_multiplier(self.type1)
            mult2 = opponent.get_type_multiplier(self.type2)

            features = np.array([[
                self.hp / self.max_hp,      # ai_hp_ratio
                self.attack,                # ai_attack
                self.sp_attack,             # ai_sp_attack
                self.speed,                 # ai_speed
                opponent.hp / opponent.max_hp,  # player_hp_ratio
                opponent.defense,           # player_defense
                opponent.sp_defense,        # player_sp_defense
                mult1,                      # mult_type1
                mult2,                      # mult_type2
            ]])

            prediction = AI_MODEL.predict(features)[0]  # 0 → type1, 1 → type2
            return self.type1 if prediction == 0 else self.type2

        # fallback if model not loaded
        return np.random.choice([self.type1, self.type2])

    def __repr__(self):
        return (f"{self.name} | {self.type1}/{self.type2} | "
                f"HP:{self.hp:.0f}/{self.max_hp:.0f} | "
                f"ATK:{self.attack} SPD:{self.speed}")

In [ ]:
#team selection
player_team = sortpoke.sample(3).reset_index(drop=True)
ai_team     = sortpoke.sample(3).reset_index(drop=True)

print("\n═══════════ YOUR TEAM ═══════════")
for i, row in player_team.iterrows():
    print(f"  [{i}] {row['name']:<20} {row['type1']} / {row['type2']}")

while True:
    try:
        choice = int(input("\nChoose your Pokemon (0, 1, 2): "))
        if choice in [0, 1, 2]:
            break
        print("  Enter 0, 1, or 2.")
    except ValueError:
        print("  Invalid input.")

player_pokemon = Pokemon(player_team.iloc[choice])
ai_pokemon     = Pokemon(ai_team.iloc[0])

print(f"\n  You  → {player_pokemon}")
print(f"  Foe  → {ai_pokemon}")

═══════════ YOUR TEAM ═══════════
  [0] Lapras               water / ice
  [1] Cutiefly             bug / fairy
  [2] Seaking              water / water

Choose your Pokemon (0, 1, 2): 2

  You  → Seaking | water/water | HP:80/80 | ATK:92 SPD:68
  Foe  → Pelipper | water/flying | HP:60/60 | ATK:50 SPD:65

player chooses which attack

In [ ]:
'''print("chosen_pokemon")
print(chosen_pokemon["type1"])
print(chosen_pokemon["type2"])
attack_choice=int(input("choose 1 or 2"))
if choice == 1:
    attack_type ="against_"+pokemon.type1
else:
    attack_type = "against_"+pokemon.type2'''

'print("chosen_pokemon")\nprint(chosen_pokemon["type1"])\nprint(chosen_pokemon["type2"])\nattack_choice=int(input("choose 1 or 2"))\nif choice == 1:\n    attack_type ="against_"+pokemon.type1\nelse:\n    attack_type = "against_"+pokemon.type2'

NameError: name 'attack_type' is not defined

## **health bar **

In [ ]:
# jab choosen card ka index hoga to we can use  something like c="against_"+player.type and then we can use typemultiplyer = player[against_type]

In [ ]:
def health_bar(poke: Pokemon):
    bar_length   = 20
    ratio        = max(poke.hp, 0) / poke.max_hp
    filled       = int(bar_length * ratio)
    bar          = "█" * filled + "-" * (bar_length - filled)
    print(f"  {poke.name:<20} HP: [{bar}] {max(poke.hp, 0):.0f}/{poke.max_hp:.0f}")

battle loop

In [ ]:
exec(open('train_ai.py').read())

Loaded 801 Pokemon.

Generated 10000 training samples.
Label distribution:
label
1    5149
0    4851
Name: count, dtype: int64

Test accuracy: 66.85%

Classification report:
              precision    recall  f1-score   support

       type1       0.67      0.61      0.64       970
       type2       0.66      0.72      0.69      1030

    accuracy                           0.67      2000
   macro avg       0.67      0.67      0.67      2000
weighted avg       0.67      0.67      0.67      2000

Feature importances:
mult_type2           0.397
mult_type1           0.382
player_hp_ratio      0.042
ai_hp_ratio          0.036
ai_sp_attack         0.030
player_defense       0.030
ai_speed             0.029
ai_attack            0.029
player_sp_defense    0.025
dtype: float64

✅ Model saved as ai_model.pkl
   Put ai_model.pkl in the same folder as pokemon_game.py

In [ ]:
import joblib
AI_MODEL = joblib.load('ai_model.pkl')
print("Model loaded!", AI_MODEL)

Model loaded! RandomForestClassifier(max_depth=8, random_state=42)

In [ ]:
# ── Battle loop ───────────────────────────────────────────────────────────────
print("\n══════════ BATTLE START ══════════\n")

while player_pokemon.hp > 0 and ai_pokemon.hp > 0:

    health_bar(player_pokemon)
    health_bar(ai_pokemon)

    # — Player turn ——————————————————————————————————————
    print(f"\n⚔  {player_pokemon.name}'s turn:")
    attack_type     = player_pokemon.choose_attack()
    multiplier      = ai_pokemon.get_type_multiplier(attack_type)
    attack          = Attack(attack_type)
    damage          = attack.damage(player_pokemon, ai_pokemon)  # ← removed multiplier
    ai_pokemon.hp  -= damage

    eff = {0.0: "has no effect", 0.5: "is not very effective", 2.0: "is super effective!"}.get(multiplier, "")
    print(f"  ➤ {player_pokemon.name} used {attack_type}! "
          f"{'(' + eff + ')  ' if eff else ''}→ {damage:.1f} dmg  (×{multiplier})")

    if ai_pokemon.hp <= 0:
        print(f"\n  💀 {ai_pokemon.name} fainted!")
        break

    # — AI turn ——————————————————————————————————————————
    print(f"\n🤖  {ai_pokemon.name}'s turn:")
    ai_type = ai_pokemon.ai_choose_attack(player_pokemon)
    ai_mult        = player_pokemon.get_type_multiplier(ai_type)
    attack         = Attack(ai_type)
    damage         = attack.damage(ai_pokemon, player_pokemon)  # ← fixed attacker/defender order
    player_pokemon.hp -= damage

    eff = {0.0: "has no effect", 0.5: "is not very effective", 2.0: "is super effective!"}.get(ai_mult, "")
    print(f"  ➤ {ai_pokemon.name} used {ai_type}! "
          f"{'(' + eff + ')  ' if eff else ''}→ {damage:.1f} dmg  (×{ai_mult})")

    if player_pokemon.hp <= 0:
        print(f"\n  💀 {player_pokemon.name} fainted!")
        break

    print()

# ── Result ───────────────────────────────────────────────────────────────────
print("\n══════════ RESULT ══════════")
if player_pokemon.hp > 0:
    print(f"  🏆 You win! {player_pokemon.name} survived with {player_pokemon.hp:.0f} HP.")
else:
    print(f"  You lost. {ai_pokemon.name} wins!")

══════════ BATTLE START ══════════

  Seaking              HP: [████████████████████] 80/80
  Pelipper             HP: [███████████████████-] 58/60

⚔  Seaking's turn:

  [1] water   [2] water
  Choose attack (1 or 2): 1
  ➤ Seaking used water! (is not very effective)  → 1.0 dmg  (×0.5)

🤖  Pelipper's turn:
  ➤ Pelipper used flying! → 17.5 dmg  (×1.0)

  Seaking              HP: [███████████████-----] 62/80
  Pelipper             HP: [███████████████████-] 57/60

⚔  Seaking's turn:

  [1] water   [2] water
  Choose attack (1 or 2): 4
  Enter 1 or 2.
  Choose attack (1 or 2): 2
  ➤ Seaking used water! (is not very effective)  → 1.0 dmg  (×0.5)

🤖  Pelipper's turn:
  ➤ Pelipper used flying! → 17.5 dmg  (×1.0)

  Seaking              HP: [███████████---------] 45/80
  Pelipper             HP: [██████████████████--] 56/60

⚔  Seaking's turn:

  [1] water   [2] water
  Choose attack (1 or 2): 2
  ➤ Seaking used water! (is not very effective)  → 1.0 dmg  (×0.5)

🤖  Pelipper's turn:
  ➤ Pelipper used flying! → 17.5 dmg  (×1.0)

  Seaking              HP: [██████--------------] 28/80
  Pelipper             HP: [██████████████████--] 55/60

⚔  Seaking's turn:

  [1] water   [2] water
  Choose attack (1 or 2): 2
  ➤ Seaking used water! (is not very effective)  → 1.0 dmg  (×0.5)

🤖  Pelipper's turn:
  ➤ Pelipper used flying! → 17.5 dmg  (×1.0)

  Seaking              HP: [██------------------] 10/80
  Pelipper             HP: [██████████████████--] 54/60

⚔  Seaking's turn:

  [1] water   [2] water
  Choose attack (1 or 2): 2
  ➤ Seaking used water! (is not very effective)  → 1.0 dmg  (×0.5)

🤖  Pelipper's turn:
  ➤ Pelipper used flying! → 17.5 dmg  (×1.0)

  💀 Seaking fainted!

══════════ RESULT ══════════
  You lost. Pelipper wins!